name: Mac Build Release
on:
  push:
    branches: 
      - actions
    tags: 
      - release/*

jobs:
  build:

    runs-on: macos

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1.0.0
    - run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - run: 
        brew install gnu-tar && 
        curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.12.sdk.tar.xz | gtar zx &&
        sudo mkdir /Applications/Xcode.app/Contents/Developer/SDKs &&
        sudo ln -s MacOSX10.12.sdk /Applications/Xcode.app/Contents/Developer/SDKs/MacOSX10.12.sdk &&
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/SDKs/MacOSX10.12.sdk
    - run: brew install sdl2
    - run: make
    - uses: actions/upload-artifact@v1
      with:
        name: dome-macosx
        path: dome
