name: Mac Build Release
on:
  push:
    branches: 
      - actions
    tags: 
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - run: sudo apt-get install libsdl2-dev
    - run: make
    - uses: actions/upload-artifact@v1
      with:
        name: dome-linux
        path: dome
