name: Mac Build Release
on:
  push:
    branches: 
      - actions
    tags: 
      - release/*

jobs:
  build:

    runs-on: [macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1.0.0
    - run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - run: brew install sdl2
    - run:
        brew install llvm &&
        echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
    - run: make
    - uses: actions/upload-artifact@v1
      with:
        name: dome-macosx
        path: dome
