name: Windows x64 Build Release
on:
  push:
    branches: 
      - actions
    tags: 
      - release/*
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: "gcc git mingw-w64-x86_64-SDL2 make"
    #- run: git config --global core.autocrlf input
    #  shell: bash
    - run: git describe --dirty
    - run: gcc -v
    - run: make CC=gcc
    - run: make
    - uses: actions/upload-artifact@v1
      with:
        name: dome-windows-x64
        path: dome.exe
