name: Linux Build Release
on:
  push:
    branches: 
      - actions
    tags: 
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - run: git fetch --prune --unshallow
    - run: sudo apt-get update
    - run: ./setup_static_linux_sdl.sh
    - run: make MODE=release ARCH=64bit
    - uses: actions/upload-artifact@v1
      with:
        name: dome-linux
        path: dome
