name: Linux Build Release
on:
  push:
    branches: 
      - actions
    tags: 
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - run: git fetch --prune --unshallow
    - run: sudo apt-get update
    - run: sudo apt-get install build-essential mercurial make cmake autoconf automake libtool libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev   libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev  libxss-dev libgl1-mesa-dev libdbus-1-dev libudev-dev libgles2-mesa-dev  libegl1-mesa-dev libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev  libsndio-dev libwayland-dev libxkbcommon-dev libdl-dev
    - run: ./setup_static_linux_sdl.sh
    - run: make MODE=release ARCH=64bit STATIC=1
    - uses: actions/upload-artifact@v1
      with:
        name: dome-linux
        path: dome
