name: Mac Build Release
on:
  push:
    branches: 
      - actions
    tags: 
      - release/*

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    
    - run: 
        export SDL_NAME=SDL2-2.0.2 ;
        curl -L https://www.libsdl.org/release/$SDL_NAME.tar.gz -o $SDL_NAME.tar.gz ;
        tar -zxvf $SDL_NAME.tar.gz ;
        cd $SDL_NAME ;
        mkdir build ;
        cd build ;
        CC=$GITHUB_WORKSPACE/$SDL_NAME/build-scripts/gcc-fat.sh  ;
        ../configure ;
        make ;
        make install
    - run: make MIN_MAC_VERSION=10.12
    - uses: actions/upload-artifact@v1
      with:
        name: dome-macosx
        path: dome
