name: Mac Build Release
on:
  push:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - run: sudo xcode-select -switch /Applications/Xcode_11.app/Contents/Developer
    - run: ./setup_static_mac_sdl.sh
    - run: make MIN_MAC_VERSION=10.12 STATIC=1 MODE=release ARCH=64bit
    - uses: actions/upload-artifact@v1
      with:
        name: dome-macosx
        path: dome
